spring:
  application:
    name: vacancies-searcher-server
  data:
    mongodb:
      host: localhost
      port: 27017
      database: vacancies
scrapper:
  providers:
    dou: false
    djinni: false
    testScrapper1: true
    testScrapper2: true