spring:
  application:
    name: vacancies-searcher-server
  data:
    mongodb:
      host: localhost
      port: 27017
      database: vacancies
scrapper:
  providers:
    dou: false
    djinni: false
    testScrapperSuccessful: true
    testScrapperPartlyFailed: true
    testScrapperFailed: true